package net.mytestfragment.com.testfragment.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.mytestfragment.com.testfragment.greendao.User;
import net.mytestfragment.com.testfragment.greendao.Level;

import net.mytestfragment.com.testfragment.greendao.UserDao;
import net.mytestfragment.com.testfragment.greendao.LevelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig levelDaoConfig;

    private final UserDao userDao;
    private final LevelDao levelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        levelDao = new LevelDao(levelDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Level.class, levelDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        levelDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

}
